### ISSUE TITLE
[POST] TensorFlow 2.0: melhores práticas e o que mudou

### ISSUE THREAD

**Issue by arnaldog12** [tensorflow-brasil/tutoriais#2]
## Tipo da #Issue

- [x] Adicionar um Post
- [ ] Adicionar um Curso
- [ ] Adicionar um Projeto
- [ ] Adicionar um Tutorial
- [ ] Traduzir algum materia para Português/BR

## Link / Referência Para o Material

[TensorFlow 2.0: melhores práticas e o que mudou](https://medium.com/data-hackers/tensorflow-2-0-melhores-práticas-e-o-que-mudou-ec56ba95b6a)

## Versão do TensorFlow

TensorFlow@2.0

**Comment by rodrigoleite89** [comment]
!Done
