### ISSUE TITLE
[TUTORIAL] Transfer Learning com Tensorflow? Mais fácil do que você imagina…

### ISSUE THREAD

**Issue by arnaldog12** [tensorflow-brasil/tutoriais#3]
## Tipo da #Issue

- [x] Adicionar um Post
- [ ] Adicionar um Curso
- [ ] Adicionar um Projeto
- [x] Adicionar um Tutorial
- [ ] Traduzir algum materia para Português/BR

## Link / Referência Para o Material

[Transfer Learning com Tensorflow? Mais fácil do que você imagina…](https://medium.com/ensina-ai/transfer-learning-com-tensorflow-mais-fácil-do-que-você-imagina-75c687fbf7be)

## Versão do TensorFlow

TensorFlow  1.9

**Comment by rodrigoleite89** [comment]
done!
