### ISSUE TITLE
[CURSO] Minicurso de TensorFlow

### ISSUE THREAD

**Issue by arnaldog12** [tensorflow-brasil/tutoriais#4]
## Tipo da #Issue

- [ ] Adicionar um Post
- [x] Adicionar um Curso
- [ ] Adicionar um Projeto
- [ ] Adicionar um Tutorial
- [ ] Traduzir algum materia para Português/BR

## Link / Referência Para o Material

[Minicurso de TensorFlow](https://github.com/arnaldog12/minicurso-tensorflow)

## Versão do TensorFlow

TensorFlow@1.0-1.13

**Comment by rodrigoleite89** [comment]
Done!
